name: ayikie_users
description: A new flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  flutter_svg: ^0.22.0
  expansion_widget: ^0.0.2
  smooth_page_indicator: ^1.0.0+2
  persistent_bottom_nav_bar: ^4.0.2
  cached_network_image: ^3.2.0
  image_cropper: ^1.4.1
  image_picker: ^0.8.3+3
  flutter_spinkit: ^5.1.0
  auto_size_text: ^3.0.0
  flutter_rating_bar: ^4.0.0
  cupertino_stepper: ^0.2.1
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.0
  intl: ^0.17.0
  intl_phone_number_input: ^0.7.0+2
  country_code_picker: ^2.0.2
  intl_phone_field: ^3.1.0
  geolocator: ^7.5.0
  flutter_paystack: ^1.0.5+1
  async: ^2.7.0
  geocode: 1.0.1
  flutter_html: ^2.2.1
  flutter_firebase_chat_core: ^1.1.0
  flutter_chat_ui: ^1.3.0
  flutter_chat_types: ^3.0.0
  file_picker: ^4.3.0
  open_file: ^3.2.0
  flutter_link_previewer: ^2.4.0
  geocoding: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.

  plugin:
    platforms:
      android:
        package: com.ayikie.ayikie_users
        pluginClass: AyikieUsersPlugin
      ios:
        pluginClass: AyikieUsersPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg





  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
