name: ayikie_main
description: A new flutter plugin project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ayikie_service:
    path: ../ayikie_service
  ayikie_users:
    path: ../ayikie_users
  http: ^0.13.3
  connectivity: ^3.0.6
  shared_preferences: ^2.0.6
  rxdart: ^0.27.1
  flutter_svg:  ^0.22.0
  pin_code_fields: ^7.3.0
  smooth_page_indicator: ^1.0.0+2
  timeline_list: ^0.0.6
  intl_phone_number_input: ^0.7.0+2
  country_code_picker: ^2.0.2
  intl_phone_field: ^3.1.0
  flutter_local_notifications: ^9.5.2
  google_sign_in: ^5.0.3
  twitter_login: ^4.2.3
  flutter_facebook_auth: ^4.3.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.ayikie.ayikie_main
        pluginClass: AyikieMainPlugin
      ios:
        pluginClass: AyikieMainPlugin

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
